# Generated by Django 3.2.7 on 2022-01-06 18:23

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(default='Nairobi', max_length=180, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(default='KE', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_agent',
            field=models.BooleanField(default=False, help_text='Are you an agent?', verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+41524204242', max_length=30, region=None, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(default='/profile_default.png', upload_to='', verbose_name='Profile Photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='top_agent',
            field=models.BooleanField(default=False, verbose_name='Top Agent'),
        ),
    ]
