# Generated by Django 3.2.7 on 2022-01-06 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='agent_buyer', to='users.user', verbose_name='Agent,Seller or Buyer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='cover_photo',
            field=models.ImageField(blank=True, default='/house_sample.jpg', null=True, upload_to='', verbose_name='Main Photo'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(default='Default description...update me please....', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('House', 'House'), ('Apartment', 'Apartment'), ('Office', 'Office'), ('Warehouse', 'Warehouse'), ('Commercial', 'Commercial'), ('Other', 'Other')], default='Other', max_length=50, verbose_name='Property Type'),
        ),
        migrations.AlterField(
            model_name='property',
            name='ref_code',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Property Reference Code'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Property Title'),
        ),
        migrations.AlterField(
            model_name='property',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Total Views'),
        ),
    ]
